FROM debian:12

# install security updates
RUN apt update \
 && apt -y upgrade \
 && apt -y full-upgrade \
 && apt -y autoremove

# install mandatory packages
RUN apt -y --no-install-recommends install \
 build-essential cpio unzip rsync file bc wget ca-certificates

# install recommended packages
RUN apt -y --no-install-recommends install \
 python3 python-is-python3 libncurses-dev

WORKDIR /build

RUN useradd --create-home sander
USER sander
